/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/google/login.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate Google SSO login
         * @description Redirects the user to Google for authentication.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to Google OAuth URL */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/google/callback.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google SSO callback
         * @description Handles the response from Google and logs the user in.
         */
        get: {
            parameters: {
                query: {
                    code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Error message on failure */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Redirect to index.php after successful login */
                302: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Log out
         * @description Destroys the user session.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to google/login.php */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/github/login.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate GitHub OAuth
         * @description Redirects the user to GitHub for account linking.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to GitHub OAuth URL */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/github/callback.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GitHub OAuth callback
         * @description Handles the response from GitHub and links the account.
         */
        get: {
            parameters: {
                query: {
                    code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to index.php with success or error status */
                302: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description Displays user projects and linked GitHub accounts.
         */
        get: {
            parameters: {
                query?: {
                    success?: string;
                    github?: string;
                    delete_project?: number;
                    csrf_token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard HTML page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Link new repository
         * @description Creates a new project by linking a GitHub repository.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/x-www-form-urlencoded": {
                        github_repo?: string;
                        github_account_id?: number;
                        csrf_token?: string;
                    };
                };
            };
            responses: {
                /** @description Redirect to index.php with success status */
                302: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project details
         * @description Displays tasks and logs for a specific project.
         */
        get: {
            parameters: {
                query: {
                    id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project details HTML page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": unknown;
                    };
                };
            };
        };
        put?: never;
        /**
         * Trigger agent
         * @description Manually triggers the Jules agent for a specific task.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/x-www-form-urlencoded": {
                        trigger_agent?: string;
                        task_id?: number;
                        csrf_token?: string;
                    };
                };
            };
            responses: {
                /** @description Project details HTML page updated with agent response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/github/webhook.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GitHub Webhook
         * @description Receives 'issues' events from GitHub.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-Hub-Signature-256": string;
                    "X-GitHub-Event": "issues";
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GitHubIssueEvent"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown;
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid signature */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to process event */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/webhook.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Webhook
         * @description Receives updates from the Telegram Bot API.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-Telegram-Bot-Api-Secret-Token": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/index.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin dashboard
         * @description User management for administrators.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Admin dashboard HTML page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": unknown;
                    };
                };
                /** @description Redirect to google/login if not logged in */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Access denied if not admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtain JWT token
         * @description Issues a JWT access token and a refresh token for the currently session-authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A pair of JWT access token and refresh token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token?: string;
                            refresh_token?: string;
                            token_type?: string;
                            expires_in?: number;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh JWT token
         * @description Exchanges a valid refresh token for a new access token and refresh token.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A new pair of JWT access token and refresh token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token?: string;
                            refresh_token?: string;
                            token_type?: string;
                            expires_in?: number;
                        };
                    };
                };
                /** @description Missing refresh token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid or expired refresh token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user projects (JSON)
         * @description Returns a list of projects associated with the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A JSON list of projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Link new repository
         * @description Creates a new project by linking a GitHub repository.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        github_repo: string;
                        github_account_id: number;
                    };
                };
            };
            responses: {
                /** @description Project created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            project_id?: number;
                            message?: string;
                        };
                    };
                };
                /** @description Missing parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project details (JSON)
         * @description Returns details for a specific project, including roadmap data.
         */
        get: {
            parameters: {
                query: {
                    /** @description Project ID */
                    id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Access denied or project not found */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Perform project action
         * @description Triggers actions like issue synchronization, creating issues from templates/roadmap, or updating settings.
         */
        post: {
            parameters: {
                query: {
                    /** @description Project ID */
                    id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        action: "sync_issues" | "create_from_template" | "create_from_roadmap" | "update_settings" | "update_notifications" | "create_github_issue";
                        /** @description Required for 'create_github_issue' */
                        title?: string;
                        /** @description Optional for 'create_github_issue' */
                        body?: string;
                        /** @description Optional labels for 'create_github_issue' */
                        labels?: string[];
                        /** @description Required for 'create_from_template' */
                        template_id?: number;
                        /** @description Parameter values for the template */
                        params?: {
                            [key: string]: string;
                        };
                        /** @description Required for 'create_from_roadmap' */
                        roadmap_name?: string;
                        /** @description Required for 'update_settings' */
                        github_repo?: string;
                        /** @description Required for 'update_settings' */
                        github_account_id?: number;
                        /** @description Required for 'update_notifications' */
                        status_settings?: {
                            [key: string]: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description Action performed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            message?: string;
                        };
                    };
                };
                /** @description Invalid action or missing parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Action failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Delete project
         * @description Deletes a project.
         */
        delete: {
            parameters: {
                query: {
                    /** @description Project ID */
                    id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tasks (JSON)
         * @description Returns a list of tasks, optionally filtered by project or status.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Project ID (optional) */
                    id?: number;
                    /** @description Filter criteria */
                    filter?: "all_open" | "github_running" | "github_passed" | "github_failed" | "jules_analyzing" | "jules_executing" | "jules_failed" | "open_issues";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A JSON list of tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/autorepeat-tasks.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List running autorepeat tasks (JSON)
         * @description Returns a list of all active autorepeat tasks for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A JSON list of tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get task details (JSON)
         * @description Returns details for a specific task.
         */
        get: {
            parameters: {
                query: {
                    /** @description Task ID */
                    id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Perform task action
         * @description Triggers actions like agent execution or PR merging for a task.
         */
        post: {
            parameters: {
                query: {
                    /** @description Task ID */
                    id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        action: "trigger_agent" | "merge_close" | "merge_close_duplicate";
                    };
                };
            };
            responses: {
                /** @description Action performed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            message?: string;
                            agent_response?: string;
                        };
                    };
                };
                /** @description Invalid action or missing parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Action failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task-logs.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get task logs (JSON)
         * @description Returns logs for a specific task.
         */
        get: {
            parameters: {
                query: {
                    /** @description Task ID */
                    id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A JSON list of task logs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskLog"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhook-logs.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhook logs (JSON)
         * @description Returns a list of webhook logs for the authenticated user or all logs if admin.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A JSON list of webhook logs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookLog"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance-logs.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List performance logs (JSON)
         * @description Returns a list of performance and API logs for the authenticated user or all logs if admin.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A JSON list of performance logs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PerformanceLog"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List issue templates (JSON)
         * @description Returns a list of issue templates for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A JSON list of templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Template"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create or update issue template
         * @description Creates a new issue template or updates an existing one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Template ID (for updates) */
                        id?: number;
                        name: string;
                        title_template: string;
                        body_template?: string;
                        parameter_config?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Template saved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Delete issue template
         * @description Deletes an issue template.
         */
        delete: {
            parameters: {
                query: {
                    /** @description Template ID */
                    id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Template not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile (JSON)
         * @description Returns the profile and configuration of the currently authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Update user profile/settings (JSON)
         * @description Updates the profile and configuration of the currently authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        jules_api_key?: string | null;
                        telegram_bot_name?: string | null;
                        telegram_bot_token?: string | null;
                        telegram_webhook_secret?: string | null;
                        notification_settings?: {
                            in_app?: boolean;
                            browser?: boolean;
                            telegram?: boolean;
                        };
                        notification_event_settings?: {
                            created?: boolean;
                            processing?: boolean;
                            ready?: boolean;
                            finished?: boolean;
                            failed?: boolean;
                            analyzing?: boolean;
                            planning?: boolean;
                            executing?: boolean;
                            verifying?: boolean;
                            implemented?: boolean;
                            checking?: boolean;
                            failed_jules?: boolean;
                            failed_pr?: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description User profile updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications (JSON)
         * @description Returns a list of notifications for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    /** @default list */
                    action?: "list" | "unread_count";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A JSON list of notifications or unread count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            notifications?: components["schemas"]["Notification"][];
                            unread_count?: number;
                            settings?: Record<string, never>;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Perform notification action
         * @description Marks notifications as read or clears all.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        action: "mark_read" | "mark_all_read" | "clear_all" | "test_broadcast";
                        notification_id?: number;
                    };
                };
            };
            responses: {
                /** @description Action performed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync-status.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get global sync status (JSON)
         * @description Returns global status counts for GitHub checks and Jules agents.
         */
        get: {
            parameters: {
                query?: {
                    /** @description If 1, skip external API calls and return cached data. */
                    fast?: 0 | 1;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Global status counts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncStatus"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin-users.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all users (Admin only)
         * @description Returns a list of all users with project counts. Requires admin privileges.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A JSON list of all users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Admin privileges required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin-db-check.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get database health check (Admin only)
         * @description Returns database connection status, missing patches, table validation, and basic data health. Requires admin privileges.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Database health check results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DbCheckResults"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Admin privileges required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin-upgrade.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get migration status (Admin only)
         * @description Returns applied and pending database patches. Requires admin privileges.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Migration status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MigrationStatus"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Admin privileges required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Apply database patches (Admin only)
         * @description Applies pending database patches. Requires admin privileges.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Patch name to apply or 'all' to apply all pending.
                         * @default all
                         */
                        patch?: string;
                    };
                };
            };
            responses: {
                /** @description Migrations process completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            message?: string;
                            logs?: string[];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Admin privileges required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example 1 */
            id?: number;
            /** @example 123456789 */
            google_id?: string;
            /** @example John Doe */
            name?: string;
            /** @example john@example.com */
            email?: string;
            /** @example https://avatar.url */
            avatar?: string | null;
            /**
             * @example user
             * @enum {string}
             */
            role?: "user" | "admin";
            /**
             * Format: date-time
             * @example 2023-10-27T10:00:00Z
             */
            created_at?: string;
            /** @example MyAgentBot */
            telegram_bot_name?: string | null;
            /** @description Masked or empty in GET responses for security. */
            telegram_bot_token?: string | null;
            /** @description Masked or empty in GET responses for security. */
            telegram_webhook_secret?: string | null;
            /** @example 123456789 */
            telegram_chat_id?: number | null;
            /** @description Masked or empty in GET responses for security. */
            jules_api_key?: string | null;
            /** @example true */
            has_jules_key?: boolean;
            /** @example 150 */
            jules_quota_usage?: number | null;
            /** @example 1000 */
            jules_quota_limit?: number | null;
            blockly_config?: {
                xml?: string;
                js?: string;
            } | null;
            github_accounts?: {
                github_account_id?: number;
                github_username?: string;
            }[];
            notification_settings?: {
                in_app?: boolean;
                browser?: boolean;
                telegram?: boolean;
            };
            notification_event_settings?: {
                created?: boolean;
                processing?: boolean;
                ready?: boolean;
                finished?: boolean;
                failed?: boolean;
                analyzing?: boolean;
                planning?: boolean;
                executing?: boolean;
                verifying?: boolean;
                implemented?: boolean;
                checking?: boolean;
                failed_jules?: boolean;
                failed_pr?: boolean;
            };
        };
        Project: {
            /** @example 1 */
            id?: number;
            /** @example 1 */
            user_id?: number;
            /** @example 1 */
            github_account_id?: number;
            /** @example google/jules */
            github_repo?: string;
            /** @example secret_123 */
            webhook_secret?: string;
            /**
             * Format: date-time
             * @example 2023-10-27T10:05:00Z
             */
            created_at?: string;
            /** @example johndoe_git */
            github_username?: string;
            blockly_config?: {
                xml?: string;
                js?: string;
            } | null;
            roadmap_data?: {
                name?: string;
                html_url?: string;
                next_task?: string | null;
            }[] | null;
            /**
             * Format: date-time
             * @example 2023-10-27T10:05:00Z
             */
            roadmap_updated_at?: string | null;
            notification_settings?: Record<string, boolean>;
        };
        Task: {
            /** @example 42 */
            id?: number;
            /** @example 1 */
            project_id?: number;
            /** @example 101 */
            issue_number?: number;
            /** @example Bug: App crashes */
            title?: string;
            /** @example Steps to reproduce... */
            body?: string;
            /**
             * @example created
             * @enum {string}
             */
            status?: "created" | "analyzing" | "planning" | "executing" | "verifying" | "checking" | "ready" | "finished" | "implemented" | "failed_jules" | "failed_pr";
            /** @example The bug is caused by... */
            agent_response?: string | null;
            /** @example https://github.com/google/jules/pull/123 */
            pr_url?: string | null;
            /** @example https://jules.google.com/task/abc-123 */
            jules_url?: string | null;
            /** @example coding */
            jules_status?: string | null;
            /** @example open */
            github_state?: string;
            /** @example google/jules */
            github_repo?: string;
            /**
             * Format: date-time
             * @example 2023-10-27T10:10:00Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @example 2023-10-27T10:15:00Z
             */
            last_synced_at?: string | null;
            /** @example 5 */
            autorepeat_remaining?: number;
            labels?: {
                name?: string;
                color?: string;
            }[];
            pr_details?: {
                title?: string;
                body?: string | null;
                state?: string;
                merged?: boolean;
                base?: {
                    ref?: string;
                };
                head?: {
                    ref?: string;
                };
                mergeable_state?: string | null;
                draft?: boolean | null;
            } | null;
            jules_messages?: {
                user?: {
                    login?: string;
                };
                body?: string;
                /** Format: date-time */
                created_at?: string;
                html_url?: string;
            }[];
        };
        TaskLog: {
            /** @example 500 */
            id?: number;
            /** @example 42 */
            task_id?: number;
            /** @example Agent triggered by user John Doe */
            message?: string;
            /**
             * @example info
             * @enum {string}
             */
            level?: "info" | "error";
            /**
             * Format: date-time
             * @example 2023-10-27T10:11:00Z
             */
            created_at?: string;
        };
        WebhookLog: {
            /** @example 1000 */
            id?: number;
            /** @example 1 */
            user_id?: number;
            /** @example john@example.com */
            user_email?: string | null;
            /** @example github/webhook.php */
            endpoint?: string;
            payload?: string | null;
            headers?: string | null;
            /** @example 200 */
            status_code?: number;
            error_message?: string | null;
            /**
             * Format: date-time
             * @example 2023-10-27T10:20:00Z
             */
            created_at?: string;
        };
        PerformanceLog: {
            /** @example 2000 */
            id?: number;
            /** @example 1 */
            user_id?: number | null;
            /** @example john@example.com */
            user_email?: string | null;
            /** @example api */
            type?: string;
            /** @example GET /api/projects */
            target?: string;
            /**
             * Format: float
             * @example 0.123
             */
            duration?: number;
            context?: Record<string, never> | null;
            /** @example 200 */
            status_code?: number | null;
            /** @example Not Found */
            error_message?: string | null;
            /**
             * Format: date-time
             * @example 2023-10-27T10:30:00Z
             */
            created_at?: string;
        };
        AdminUser: {
            /** @example 1 */
            id?: number;
            /** @example 123456789 */
            google_id?: string | null;
            /** @example 987654321 */
            github_id?: string | null;
            /** @example John Doe */
            name?: string;
            /** @example john@example.com */
            email?: string;
            /** @example https://avatar.url */
            avatar?: string | null;
            /**
             * @example user
             * @enum {string}
             */
            role?: "user" | "admin";
            /**
             * Format: date-time
             * @example 2023-10-27T10:00:00Z
             */
            created_at?: string;
            /** @example 5 */
            project_count?: number;
        };
        Template: {
            /** @example 1 */
            id?: number;
            /** @example Bug Report */
            name?: string;
            /** @example Bug: %1 */
            title_template?: string;
            /** @example Steps to reproduce: %2 */
            body_template?: string | null;
            parameter_config?: {
                [key: string]: string;
            } | null;
            /**
             * Format: date-time
             * @example 2023-10-27T10:00:00Z
             */
            created_at?: string;
        };
        DbCheckResults: {
            connection_status?: {
                status?: string;
                driver?: string;
                version?: string;
                message?: string | null;
            };
            missing_patches?: string[];
            table_status?: {
                table?: string;
                exists?: boolean;
                rows?: number;
                error?: string | null;
            }[];
            basic_data_status?: {
                name?: string;
                status?: string;
                message?: string;
            }[];
        };
        MigrationStatus: {
            applied?: string[];
            pending?: string[];
        };
        Notification: {
            notification_id?: number;
            user_id?: number;
            /** @description HTML formatted title */
            title?: string;
            /** @description HTML formatted message */
            message?: string;
            /** @description Plain text title */
            title_plain?: string;
            /** @description Plain text message */
            message_plain?: string;
            github_repo?: string | null;
            /** @enum {integer} */
            is_read?: 0 | 1;
            /** Format: date-time */
            created_at?: string;
            data?: {
                source_url?: string;
            } | null;
        };
        SyncStatus: {
            status?: string;
            quota_usage?: number;
            quota_limit?: number;
            total_tasks?: number;
            open_issues?: number;
            completed_tasks?: number;
            jules_analyzing?: number;
            jules_executing?: number;
            jules_failed?: number;
            github_running?: number;
            github_passed?: number;
            github_failed?: number;
            telegram_connected?: boolean;
        };
        GitHubIssueEvent: {
            /** @example opened */
            action?: string;
            issue?: {
                /** @example 101 */
                number?: number;
                /** @example Bug: App crashes */
                title?: string;
                /** @example Steps to reproduce... */
                body?: string;
            };
            repository?: {
                /** @example google/jules */
                full_name?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
