<?php

namespace App;

/**
 * Service for executing sandboxed JavaScript logic generated by Blockly.
 */
class SandboxService
{
    public function __construct(
        private Database $db,
        private ?GitHubService $githubService = null,
        private ?NotificationService $notificationService = null,
        private ?JulesService $julesService = null
    ) {
    }

    /**
     * Executes the given JavaScript code in a sandboxed environment.
     *
     * @param int $userId The user ID for context.
     * @param int $taskId The task ID for context.
     * @param string $jsCode The JavaScript code to execute.
     * @param array $eventContext Additional event metadata.
     * @param string $source The source of the automation (e.g., 'Global', 'Local').
     * @param bool $dryRun Whether to perform a dry run without side effects.
     * @return bool True if execution was successful.
     */
    public function execute(int $userId, int $taskId, string $jsCode, array $eventContext = [], string $source = 'unknown', bool $dryRun = false): bool
    {
        $logger = Logger::getInstance($this->db);
        $taskModel = new Task($this->db);
        $projectModel = new Project($this->db);

        $logger->log($userId, $taskId, "Executing [$source] Blockly automation" . ($dryRun ? " (DRY RUN)" : "") . "...", 'info');

        $task = $taskModel->findById($taskId);
        if (!$task) {
            $logger->log($userId, $taskId, "SandboxService: Task not found.", 'error');
            return false;
        }

        $project = $projectModel->findById($task['project_id']);
        if (!$project) {
            $logger->log($userId, $taskId, "SandboxService: Project not found.", 'error');
            return false;
        }

        // Prepare context for the runner
        $eventContext['automation_source'] = $source;
        $context = [
            'event' => $eventContext,
            'task' => [
                'task_id' => (int)$task['task_id'],
                'issue_number' => (int)$task['issue_number'],
                'title' => $task['title'],
                'status' => $task['status'],
                'labels' => json_decode($task['github_data'], true)['labels'] ?? []
            ],
            'project' => [
                'project_id' => (int)$project['project_id'],
                'github_repo' => $project['github_repo']
            ]
        ];

        $payload = json_encode([
            'code' => $jsCode,
            'context' => $context
        ]);

        $runnerPath = __DIR__ . '/../../scripts/blockly-runner.js';
        $descriptorspec = [
            0 => ["pipe", "r"], // stdin
            1 => ["pipe", "w"], // stdout
            2 => ["pipe", "w"]  // stderr
        ];

        $process = proc_open("node " . escapeshellarg($runnerPath), $descriptorspec, $pipes);

        if (is_resource($process)) {
            fwrite($pipes[0], $payload);
            fclose($pipes[0]);

            $output = stream_get_contents($pipes[1]);
            fclose($pipes[1]);

            $error = stream_get_contents($pipes[2]);
            fclose($pipes[2]);

            $returnValue = proc_close($process);

            if ($returnValue !== 0) {
                $logger->log($userId, $taskId, "SandboxService: Runner exited with error ($returnValue): $error", 'error');
                return false;
            }

            $result = json_decode($output, true);
            if (!$result) {
                $logger->log($userId, $taskId, "SandboxService: Failed to parse runner output: $output", 'error');
                return false;
            }

            // Log runner internal logs
            if (!empty($result['logs'])) {
                foreach ($result['logs'] as $log) {
                    $logger->log($userId, $taskId, "Blockly Log: $log", 'info');
                }
            }

            if (!$result['success']) {
                $logger->log($userId, $taskId, "SandboxService: Execution failed: " . ($result['error'] ?? 'Unknown error'), 'error');
                return false;
            }

            // Dispatch actions
            return $this->dispatchActions($userId, $taskId, $project, $task, $result['actions'] ?? [], $source, $dryRun);
        }

        $logger->log($userId, $taskId, "SandboxService: Failed to start runner process.", 'error');
        return false;
    }

    /**
     * Dispatches the actions generated by the sandbox.
     */
    private function dispatchActions(int $userId, int $taskId, array $project, array $task, array $actions, string $source, bool $dryRun): bool
    {
        $logger = Logger::getInstance($this->db);
        $success = true;

        foreach ($actions as $action) {
            $type = $action['type'] ?? '';
            try {
                switch ($type) {
                    case 'notify':
                        $logger->log($userId, $taskId, "Blockly Action [$source]: " . ($dryRun ? "(DRY RUN) Would have notified user" : "Notifying user"), 'info');
                        if (!$dryRun && $this->notificationService) {
                            $this->notificationService->notify(
                                $userId,
                                'blockly_action',
                                "Blockly Notification",
                                $action['message'] ?? '',
                                [
                                    'task_id' => $taskId,
                                    'project_id' => $project['project_id'],
                                    'is_system' => true
                                ]
                            );
                        }
                        break;

                    case 'merge':
                        $prNumber = $this->githubService ? $this->githubService->extractPrNumber($task['pr_url'] ?? '') : null;
                        if ($prNumber) {
                            $logger->log($userId, $taskId, "Blockly Action [$source]: " . ($dryRun ? "(DRY RUN) Would have merged PR #$prNumber" : "Merged PR #$prNumber"), 'info');
                            if (!$dryRun && $this->githubService) {
                                $this->githubService->mergePullRequest($project['github_repo'], $prNumber, "Merged via Blockly Automation");
                            }
                        } else {
                            $logger->log($userId, $taskId, "Blockly Action [$source]: Merge failed - No PR URL found.", 'warning');
                        }
                        break;

                    case 'duplicate':
                        $logger->log($userId, $taskId, "Blockly Action [$source]: " . ($dryRun ? "(DRY RUN) Would have requested duplication" : "Duplication requested (logged)"), 'info');
                        break;

                    case 'setLabel':
                        if (!empty($action['label'])) {
                            $logger->log($userId, $taskId, "Blockly Action [$source]: " . ($dryRun ? "(DRY RUN) Would have added label '{$action['label']}'" : "Added label '{$action['label']}'"), 'info');
                            if (!$dryRun && $this->githubService) {
                                $this->githubService->addLabel($project['github_repo'], (int)$task['issue_number'], $action['label']);
                            }
                        }
                        break;

                    case 'removeLabel':
                        if (!empty($action['label'])) {
                            $logger->log($userId, $taskId, "Blockly Action [$source]: " . ($dryRun ? "(DRY RUN) Would have removed label '{$action['label']}'" : "Removed label '{$action['label']}'"), 'info');
                            if (!$dryRun && $this->githubService) {
                                $this->githubService->removeLabel($project['github_repo'], (int)$task['issue_number'], $action['label']);
                            }
                        }
                        break;

                    case 'renameLabel':
                        if (!empty($action['oldLabel']) && !empty($action['newLabel'])) {
                            $logger->log($userId, $taskId, "Blockly Action [$source]: " . ($dryRun ? "(DRY RUN) Would have renamed label '{$action['oldLabel']}' to '{$action['newLabel']}'" : "Renamed label '{$action['oldLabel']}' to '{$action['newLabel']}'"), 'info');
                            if (!$dryRun && $this->githubService) {
                                $this->githubService->removeLabel($project['github_repo'], (int)$task['issue_number'], $action['oldLabel']);
                                $this->githubService->addLabel($project['github_repo'], (int)$task['issue_number'], $action['newLabel']);
                            }
                        }
                        break;

                    case 'postComment':
                        if (!empty($action['comment'])) {
                            $logger->log($userId, $taskId, "Blockly Action [$source]: " . ($dryRun ? "(DRY RUN) Would have posted comment" : "Posted comment"), 'info');
                            if (!$dryRun && $this->githubService) {
                                $this->githubService->postComment($project['github_repo'], (int)$task['issue_number'], $action['comment']);
                            }
                        }
                        break;

                    case 'triggerAgent':
                        $logger->log($userId, $taskId, "Blockly Action [$source]: " . ($dryRun ? "(DRY RUN) Would have triggered Agent" : "Triggered Agent"), 'info');
                        if (!$dryRun && $this->julesService) {
                            $this->julesService->triggerAgent($task);
                        }
                        break;

                    default:
                        $logger->log($userId, $taskId, "SandboxService [$source]: Unknown action type '$type'", 'warning');
                }
            } catch (\Exception $e) {
                $logger->log($userId, $taskId, "SandboxService: Action '$type' failed: " . $e->getMessage(), 'error');
                $success = false;
            }
        }

        return $success;
    }
}
