<?php

namespace App;

/**
 * Service for executing sandboxed JavaScript logic generated by Blockly.
 */
class SandboxService
{
    public function __construct(private Database $db)
    {
    }

    /**
     * Executes the given JavaScript code in a sandboxed environment.
     *
     * @param int $userId The user ID for context.
     * @param int $taskId The task ID for context.
     * @param string $jsCode The JavaScript code to execute.
     * @param array $eventContext Additional event metadata.
     * @return bool True if execution was successful.
     */
    public function execute(int $userId, int $taskId, string $jsCode, array $eventContext = []): bool
    {
        // Placeholder for future implementation of Node.js runner or v8js
        Logger::getInstance($this->db)->log($userId, $taskId, "SandboxService: Execution requested (stub). JS length: " . strlen($jsCode), 'info');

        // In the future, this will:
        // 1. Prepare the JSON context (event, task, project).
        // 2. Call scripts/blockly-runner.js via shell_exec or similar.
        // 3. Parse the output actions and dispatch them via GitHubService/NotificationService.

        return true;
    }
}
