const vm = require('vm');

/**
 * Blockly Execution Runner (Node.js)
 *
 * This script is responsible for executing the JavaScript generated by Blockly
 * in a secure, sandboxed environment. It receives the code and context via stdin
 * and outputs the resulting actions as JSON to stdout.
 */

// Read input from stdin
let inputData = '';
process.stdin.on('data', chunk => {
    inputData += chunk;
});

process.stdin.on('end', () => {
    try {
        const input = JSON.parse(inputData);
        const { code, context } = input;

        if (!code) {
            throw new Error('No code provided for execution.');
        }

        const result = executeSandbox(code, context || {});
        console.log(JSON.stringify(result));
    } catch (err) {
        console.log(JSON.stringify({
            success: false,
            error: err.message,
            actions: [],
            logs: []
        }));
        process.exit(0); // Exit gracefully so PHP can parse the error JSON
    }
});

function executeSandbox(code, context) {
    const actions = [];
    const logs = [];

    // Helper to log within the sandbox
    const sandboxLog = (msg) => logs.push(String(msg));

    // Define the sandbox environment
    const sandbox = {
        // Core Event Trigger
        onEvent: (eventType, callback) => {
            if (context.event && context.event.type === eventType) {
                try {
                    callback(context.event);
                } catch (e) {
                    sandboxLog(`Error in onEvent callback: ${e.message}`);
                }
            }
        },

        // Action Proxies
        notify: (message) => {
            actions.push({ type: 'notify', message });
        },
        merge: () => {
            actions.push({ type: 'merge' });
        },
        duplicate: () => {
            actions.push({ type: 'duplicate' });
        },
        setLabel: (label) => {
            actions.push({ type: 'setLabel', label });
        },
        removeLabel: (label) => {
            actions.push({ type: 'removeLabel', label });
        },
        renameLabel: (oldLabel, newLabel) => {
            actions.push({ type: 'renameLabel', oldLabel, newLabel });
        },
        postComment: (comment) => {
            actions.push({ type: 'postComment', comment });
        },
        triggerAgent: () => {
            actions.push({ type: 'triggerAgent' });
        },

        // Predicate Proxies (Logic)
        readLabel: (labelName) => {
            const labels = context.task?.labels || [];
            return labels.some(l => {
                const name = typeof l === 'string' ? l : (l.name || '');
                return name.toLowerCase() === labelName.toLowerCase();
            });
        },
        isTaskReady: () => {
            return context.task?.status === 'ready';
        },

        // Allow basic JS utilities
        console: {
            log: sandboxLog,
            error: sandboxLog,
            warn: sandboxLog
        },
        JSON: JSON,
        Math: Math,
        Array: Array,
        Object: Object,
        String: String,
        Number: Number,
        Boolean: Boolean,
        Date: Date
    };

    try {
        const script = new vm.Script(code);
        const vmContext = vm.createContext(sandbox);

        // Execute with timeout to prevent infinite loops
        script.runInContext(vmContext, { timeout: 1000 });

        return {
            success: true,
            actions,
            logs
        };
    } catch (err) {
        return {
            success: false,
            error: err.message,
            actions,
            logs
        };
    }
}
